name: Release for Windows

on: [ push, pull_request ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  release_windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: latest

      - name: Install Node.js and pnpm
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build-all
      - run: pnpm cli --help
      - run: pnpm dev:cli --help

      - name: Build native executable
        if: ${{ startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v') }}
        run: pnpm install --network-timeout 1000000 && pnpm package-win
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      #      - name: Setup dotnet env for signing
      #        if: ${{ startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v') }}
      #        uses: actions/setup-dotnet@v1
      #        with:
      #          dotnet-version: ${{ env.DOTNET_VERSION }}
      #
      #      - name: Get files to sign
      #        if: ${{ startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v') }}
      #        run: (Get-ChildItem -File bin/win | where {$_.extension -in ".exe"}).FullName >> bin/win/files-to-sign.txt
      #
      #      - name: Sign with azure service
      #        if: ${{ startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v') }}
      #        uses: fluffy-bunny/action-azuresigntool@v0.1dev
      #        with:
      #          azure_sign_tool_credentials: ${{ secrets.AZURE_SIGN_TOOL_CREDENTIALS_MANAGED_IDENTITY }}
      #          azure_sign_tool_assembly: tools/AzureSignTool-DEV/netcoreapp2.1/any/AzureSignTool.dll
      #          files_to_sign: bin/win/files-to-sign.txt

      - name: Release assets
        if: ${{ startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "bin/win/*.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
